version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./yoon.postman_collection.json
workflows:
  example-workflow:
    jobs:
      - newman-collection-run
